version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_NAME: guidex
      MYSQL_ROOT_PASSWORD: password

    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Expose Vite dev server port
    volumes:
      - ./frontend:/app  # Mount local code to container
      - /app/node_modules  # Prevent overwriting node_modules
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: guidex
      MYSQL_PASSWORD: password
    
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

