SCHOOLS = {
    "Ankara Fen Lisesi": "Ankara",
    "İzmir Fen Lisesi": "İzmir",
    "Atatürk Lisesi": "İzmir",
    "Tofaş Fen Lisesi": "Bursa",
    "Adana Fen Lisesi": "Adana",
    "Ankara Pursaklar Fen Lisesi": "Ankara",
    "Osman Ulubaş Kayseri Fen Lisesi": "Kayseri",
    "Prof. Dr. Aziz Sancar Fen Lisesi": "Ankara",
    "Yusuf Ziya Öner Fen Lisesi": "Antalya",
    "Nilüfer Borsa İstanbul Fen Lisesi": "Bursa",
    "Eyüp Aygar Fen Lisesi": "Mersin",
    "Erbakır Fen Lisesi": "Denizli",
    "Aydın Fen Lisesi": "Aydın",
    "Buca İnci-Özer Tırnaklı Fen Lisesi": "İzmir",
    "Meram Fen Lisesi": "Konya",
    "Atatürk Anadolu Lisesi": "Ankara",
    "Samsun Garip Zeycan Yıldırım Fen Lisesi": "Samsun",
    "Sümer Fen Lisesi": "Kayseri",
    "Kocaeli Fen Lisesi": "Kocaeli",
    "Vehbi Dinçerler Fen Lisesi": "Gaziantep",
    "Seyhan Borsa İstanbul Fen Lisesi": "Adana",
    "Cumhuriyet Fen Lisesi": "Ankara",
    "Eskişehir Fatih Fen Lisesi": "Eskişehir",
    "Trabzon Merkez Fen Lisesi": "Trabzon",
    "Özdemir Bayraktar Havacılık ve Uzay Teknolojileri MTAL": "Ankara",
    "Manisa Fen Lisesi": "Manisa",
    "Bornova Anadolu Lisesi": "İzmir",
    "Bursa Anadolu Lisesi": "Bursa",
    "Malatya Erman Ilıcak Fen Lisesi": "Malatya",
    "Rekabet Kurumu Cumhuriyet Fen Lisesi": "Diyarbakır",
    "Nazilli Fen Lisesi": "Aydın",
    "Yahya Akel Fen Lisesi": "Mersin",
    "Keçiören Vatansever Şehit Aydoğan Aydın Fen Lisesi": "Ankara",
    "AYDEM Fen Lisesi": "Denizli",
    "Ahmet Hamdi Gökbayrak Fen Lisesi": "Bursa",
    "Mahmut Sami Ramazanoğlu Anadolu İHL": "Konya",
    "Antalya Anadolu Lisesi": "Antalya",
    "Isparta Süleyman Demirel Fen Lisesi": "Isparta",
    "Ankara Erman Ilıcak Fen Lisesi": "Ankara",
    "Ebru Nayim Fen Lisesi": "Tekirdağ",
    "Aziz Atik Fen Lisesi": "Samsun",
    "Yenimahalle Fen Lisesi": "Ankara",
    "TOBB Fen Lisesi": "Gaziantep",
    "Halil Kale Fen Lisesi": "Manisa",
    "TOBB Osmaniye Fen Lisesi": "Osmaniye",
    "Kaya Karakaya Fen Lisesi": "Elazığ",
    "Muammer Dereli Fen Lisesi": "Kocaeli",
    "Süleyman Demirel Fen Lisesi": "Afyonkarahisar",
    "Erzurum İbrahim Hakkı Fen Lisesi": "Erzurum",
    "İzmir Kız Lisesi": "İzmir",
    "Kayseri Fen Lisesi": "Kayseri",
    "Trabzon Yomra Fen Lisesi": "Trabzon",
    "ASELSAN MTAL": "Ankara",
    "Adana Anadolu Lisesi": "Adana",
    "Karatay Fen Lisesi": "Konya",
    "Tokat Milli Piyango İhya Balak Fen Lisesi": "Tokat",
    "Borsa İstanbul Fen Lisesi": "Diyarbakır",
    "Prof. Dr. İlhan Kılıçözlü Fen Lisesi": "Kırşehir",
    "Yücel Boru Fen Lisesi": "Kocaeli",
    "Canik Fen Lisesi": "Samsun",
    "Eskişehir Anadolu Lisesi": "Eskişehir",
    "Selçuklu Fen Lisesi": "Konya",
    "Menteşe TOBB Fen Lisesi": "Muğla",
    "Yaşar Kımıl Fen Lisesi": "Denizli",
    "Özkent Akbilek Fen Lisesi": "Ankara",
    "Kütahya Nafi Güral Fen Lisesi": "Kütahya",
    "Ahmet Erdem Anadolu Lisesi": "Bursa",
    "Nuh Mehmet Küçükçalık Anadolu Lisesi": "Kayseri",
    "Kahramanmaraş TOBB Fen Lisesi": "Kahramanmaraş",
    "Çanakkale Fen Lisesi": "Çanakkale",
    "Sivas Fen Lisesi": "Sivas",
    "Hüseyin Girenes Fen Lisesi": "Antalya",
    "Sakarya Cevat Ayhan Fen Lisesi": "Sakarya",
    "Aksaray Şehit Pilot Hamza Gümüşsoy Fen Lisesi": "Aksaray",
    "Sesim Sarpkaya Fen Lisesi": "Mersin",
    "Macide-Ramiz Taşkınlar Fen Lisesi": "Manisa",
    "Batman Fen Lisesi": "Batman",
    "Adem-Tolunay Anadolu Lisesi": "Antalya",
    "Şehit Turgut Solak Fen Lisesi": "Balıkesir",
    "Van Türk Telekom Fen Lisesi": "Van",
    "Antalya TOBB Fen Lisesi": "Antalya",
    "Abdulkadir Konukoğlu Fen Lisesi": "Gaziantep",
    "Karşıyaka Cihat Kora Anadolu Lisesi": "İzmir",
    "Şehit Özcan Kan Fen Lisesi": "Kocaeli",
    "Şanlıurfa Fen Lisesi": "Şanlıurfa",
    "Buca Fatma Saygın Anadolu Lisesi": "İzmir",
    "Gazi Anadolu Lisesi": "Ankara",
    "Ankara Atatürk Lisesi": "Ankara",
    "15 Temmuz Şehitleri Fen Lisesi": "Çorum",
    "Kepez Mahmut Celalettin Ökten Anadolu İHL": "Antalya",
    "Altıeylül Fen Lisesi": "Balıkesir",
    "Şükrü Şankaya Anadolu Lisesi": "Bursa",
    "Vali Aydın Arslan Fen Lisesi": "Diyarbakır",
    "Ordu Fen Lisesi": "Ordu",
    "Sami Yangın Anadolu Lisesi": "Kayseri",
    "Meram Anadolu Lisesi": "Konya",
    "Çiğli Fen Lisesi": "İzmir",
    "Kastamonu Fen Lisesi": "Kastamonu",
    "Ortaklar Fen Lisesi": "Aydın",
    "ÇEAS Anadolu Lisesi": "Adana",
}
